module Bjolang.Parser

open Lexer

// --- S-Expression Types ---
type SExpr =
    | SAtom of LexedToken
    | SList of SExpr list * Range

let getRange =
    function
    | SAtom t -> t.Range
    | SList(_, r) -> r

// --- AST Types ---
// Every node carries a Range to enable #line emission.

type FType =
    | TName of string * Range
    | TApp of string * FType list * Range
    // (-> MandatoryTypes... (#:key KeyType)... #:rest RestElemType ReturnType)
    | TArrow of FType list * (string * FType) list * FType option * FType * Range

type UnionCase =
    | SimpleCase of string * Range
    | DataCase of string * FType list * Range

type RecordField =
    { Name: string
      Type: FType
      Range: Range }

type TypeDefKind =
    | Alias of FType
    | Union of UnionCase list
    /// A record, and whether it is a *value* type.
    ///
    /// `Struct` used to be nothing but an accepted spelling of `Record`. It now
    /// means what it says: the type compiles to a C# `record struct` rather than
    /// a `record`, so it lives in its enclosing local or field rather than on
    /// the heap. Both are immutable and both compare by value, so the choice is
    /// about representation and nothing else — but it is not free either way: a
    /// large struct is copied where a record would have passed a reference, and
    /// a struct may not contain itself, which C# reports.
    | Record of RecordField list * bool

type TypeDef =
    { Name: string
      TypeArgs: string list
      Kind: TypeDefKind
      Range: Range }


type Pattern =
    | PWildcard of Range
    | PIdent of string * Range
    | PInt of string * Range
    | PString of string * Range
    | PKeyword of string * Range
    | PQuotedSymbol of string * Range
    | PList of Pattern list * Pattern option * Range // (items, optional tail, range)
    | PVec of Pattern list * Pattern option * Range // (items, optional tail, range)
    | PConstruct of string * Pattern list * Range

and Expr =
    | EInt of string * Range
    | EString of string * Range
    | EQuotedSymbol of string * Range
    | EKeyword of string * Range
    | EIdent of string * Range
    | ETuple of Expr list * Range
    | EApp of Expr * Expr list * Range
    | ECast of FType * Expr * Range
    // ELet (name, isFun, args, typeAnn, value, restOfScope, range)
    | ELet of string * bool * string list * FType option * Expr * Expr * Range
    /// A binding that is deliberately *not* generalized.
    ///
    /// `let` generalizes whatever the value restriction admits, and a bare
    /// nullary constructor is admitted. That is wrong for anything whose type
    /// arguments have to be pinned down by the *body* rather than by the value:
    /// each use instantiates a fresh variable, nothing ever unifies them, and
    /// codegen emits a type parameter that was never declared.
    ///
    /// Binding the value's own type unquantified is the only thing that is both
    /// monomorphic and concrete-headed at the point the body is checked — which
    /// is what an associated-type projection needs. A lambda parameter is
    /// monomorphic too, but its type is still a bare metavariable there, so the
    /// projection has nothing to resolve against.
    ///
    /// Generated by desugarings; `(let/mono name value body)` exists as surface
    /// syntax only so that an exported inline template can round-trip.
    | ELetMono of string * Expr * Expr * Range
    // ELetRec (bindings, restOfScope, range)
    // binding tuple: (name, isFun, args, typeAnn, value)
    | ELetRec of (string * bool * string list * FType option * Expr) list * Expr * Range
    | ELetTuple of string list * Expr * Expr * Range
    | ELetMutable of string * FType option * Expr * Expr * Range
    | ESet of string * Expr * Range
    | EIf of Expr * Expr * Expr * Range
    /// `(when cond body...)`, and with the flag set, `(unless cond body...)`:
    /// a conditional with only one arm, evaluated for effect.
    | EWhen of Expr * Expr * bool * Range
    | EFun of string list * Expr * Range
    | ERecord of (string * Expr) list * Range
    | ERecordUpdate of string * (string * Expr) list * Range
    | EGetField of Expr * string * Range
    | EList of Expr list * Range
    | EVec of Expr list * Range
    | EMatch of Expr * (Pattern * Expr option * Expr) list * Range
    | ETryFinally of Expr * Expr * Range
    /// `(seq body...)`: a lazy sequence. The body is not a value — it is run,
    /// one `yield` at a time, by whoever enumerates the sequence.
    | ESeq of Expr * Range
    /// `(yield v)`: hand `v` to the enclosing `seq`'s consumer.
    | EYield of Expr * Range
    /// `(yield-from s)`: hand over every element of `s` in turn.
    | EYieldFrom of Expr * Range

and DefunArg =
    | MandatoryArg of string
    | KeywordArg of string * Expr              // (#:keyword defaultValue)
    | RestArg of string                        // #:rest name

type ImportSpec =
    | RelativePath of string
    | ModulePath of string list

type Decl =
    | DSignature of string * FType * (string * string) list * Range
    | DImport of ImportSpec list * Range
    | DExport of string list * Range
    // Re-exports bindings this module imported from elsewhere. Unlike `export`,
    // the names are not required to have a signature in this module — they
    // already have one where they were defined.
    | DReExport of string list * Range
    | DModule of string * Decl list * Range
    | DDef of string * Expr * Range
    | DDefTuple of string list * Expr * Range
    | DDefMutable of string * Expr * Range
    | DDefun of string * DefunArg list * Expr * Range
    | DType of TypeDef list * Range
    | DTypeRec of TypeDef list * Range
    // DTrait (Name, ImplementorVar, HoleArity, AssociatedTypes, Signatures, Range)
    //
    // `HoleArity` is how many arguments the implementor was written applied to.
    // `(def/trait (Show %c) ...)` gives 0 and means an interface trait;
    // `(def/trait (Monad (%m %a)) ...)` gives 1 and means an inline-only one.
    | DTrait of string * string * int * string list * (string * FType) list * Range
    | DExtern of string * FType * (string * string) list * Range

    // One inline-trait method body, read back out of a compiled module's
    // metadata. It is the *untyped* expression: re-inferring it at the splice is
    // what gives it a type its trait signature cannot express.
    // DInlineImpl (TraitName, MethodName, Ctor, OriginModule, Params, Body, Qualification, Range)
    | DInlineImpl of string * string * string * string * string list * Expr * (string * string) list * Range
    
    // DImpl (TraitName, TargetType, AssociatedTypeBindings, Methods, Range)
    | DImpl of string * FType * (string * FType) list * Decl list * Range

    // A declaration-only implementation: it records that the target type
    // implements the trait, and what its associated types are, without carrying
    // any method bodies. This is what a compiled module's metadata exports —
    // the methods themselves already live in that assembly.
    // DImplExtern (TraitName, TargetType, AssociatedTypeBindings, Range)
    | DImplExtern of string * FType * (string * FType) list * Range

// --- Parser ---

let rec parsePattern (s: SExpr) : Pattern =
    let r = getRange s

    match s with
    | SAtom { Token = Symbol "_" } -> PWildcard r
    | SAtom { Token = Symbol sym } -> 
        if System.Char.IsUpper(sym.[0]) then PConstruct(sym, [], r)
        else PIdent(sym, r)
    | SAtom { Token = NumberLit n } -> PInt(n, r)
    | SAtom { Token = StringLit str } -> PString(str, r)
    | SAtom { Token = Keyword kw } -> PKeyword(kw, r)
    | SAtom { Token = QuotedSymbol sym } -> PQuotedSymbol(sym, r)

    // Special handling for List/Vec patterns and the spread operator
    | SList(SAtom { Token = Symbol "List" } :: args, _) ->
        let elements, tail = parseSpreadArgs r args
        PList(elements, tail, r)

    // `(Vec a b c ...)` and the bracket literal form `[a b c ...]`, which the
    // reader rewrites to `(vec-literal a b c ...)`.
    | SList(SAtom { Token = Symbol("Vec" | "vec-literal") } :: args, _) ->
        let elements, tail = parseSpreadArgs r args
        PVec(elements, tail, r)

    | SList(SAtom { Token = Symbol name } :: args, _) -> PConstruct(name, List.map parsePattern args, r)

    | SList([], _) -> PList([], None, r) // Empty list pattern

    | _ -> failwithf $"Invalid pattern at line %d{r.Start.Line}"

/// Splits the arguments of a sequence pattern into its fixed leading elements
/// plus an optional trailing rest pattern introduced by `...`.
/// For example `a b c ...` yields ([a; b], Some c), binding `c` to the rest.
and parseSpreadArgs (r: Range) (args: SExpr list) : Pattern list * Pattern option =
    let rec go acc items =
        match items with
        | [] -> (List.rev acc, None)
        // Matches `c ...` at the end of the sequence
        | [ tailItem; SAtom { Token = Spread } ] -> (List.rev acc, Some(parsePattern tailItem))
        // Fails if spread is used incorrectly (e.g., in the middle of the sequence)
        | SAtom { Token = Spread } :: _ -> failwithf $"Invalid use of spread operator at line %d{r.Start.Line}"
        | head :: tail -> go (parsePattern head :: acc) tail

    go [] args

let parseArrowType (items: SExpr list) (r: Range) : FType =
    if items.IsEmpty then failwithf $"Arrow type must have at least a return type at line %d{r.Start.Line}"
    let returnTypeExpr = List.last items
    let argItems = List.take (items.Length - 1) items

    let rec parseArrowTypeInner (s: SExpr) : FType =
        let r = getRange s
        match s with
        | SAtom { Token = QuotedSymbol sym } -> TName("'" + sym, r)
        | SAtom { Token = Symbol sym }
        | SAtom { Token = TypeVar sym } -> TName(sym, r)
        | SList(SAtom { Token = Symbol name } :: typeArgs, _) -> TApp(name, List.map parseArrowTypeInner typeArgs, r)
        // A type variable in *applied* position: `(%m %a)`. Only an inline
        // trait's constructor variable can be written this way, and the leading
        // quote is what tells `resolveTemplate` it is the hole rather than a
        // constructor named `m`.
        | SList(SAtom { Token = QuotedSymbol sym } :: typeArgs, _) ->
            TApp("'" + sym, List.map parseArrowTypeInner typeArgs, r)
        | _ -> failwithf $"Invalid type syntax in arrow type at line %d{r.Start.Line}"

    let rec collectArgs mandatory keywords argItems =
        match argItems with
        | [] -> TArrow(List.rev mandatory, List.rev keywords, None, parseArrowTypeInner returnTypeExpr, r)
        | [SAtom { Token = Keyword "rest" }] ->
            failwithf $"Expected rest element type after #:rest at line %d{r.Start.Line}"
        | SAtom { Token = Keyword "rest" } :: restTypeExpr :: [] ->
            TArrow(List.rev mandatory, List.rev keywords, Some (parseArrowTypeInner restTypeExpr), parseArrowTypeInner returnTypeExpr, r)
        | SList(SAtom { Token = Keyword name } :: [ typeExpr ], _) :: rest ->
            collectArgs mandatory ((name, parseArrowTypeInner typeExpr) :: keywords) rest
        | item :: rest when keywords.IsEmpty ->
            collectArgs (parseArrowTypeInner item :: mandatory) keywords rest
        | _ -> failwithf $"Mandatory types must come before keyword/rest types in arrow type at line %d{r.Start.Line}"

    collectArgs [] [] argItems

let rec parseType (s: SExpr) : FType =
    let r = getRange s

    match s with
    | SAtom { Token = QuotedSymbol sym } -> TName("'" + sym, r)  // %a in source → 'a internally
    | SAtom { Token = Symbol sym }
    | SAtom { Token = TypeVar sym } -> TName(sym, r)
    | SList(SAtom { Token = Symbol "->" } :: arrowArgs, _) -> parseArrowType arrowArgs r
    | SList(SAtom { Token = Symbol name } :: typeArgs, _) -> TApp(name, List.map parseType typeArgs, r)
    // `(%m %a)` — a type variable applied to arguments. See `parseArrowTypeInner`.
    | SList(SAtom { Token = QuotedSymbol sym } :: typeArgs, _) ->
        TApp("'" + sym, List.map parseType typeArgs, r)
    | _ -> failwithf $"Invalid type syntax at line %d{r.Start.Line}"

let parseUnionCase (s: SExpr) : UnionCase =
    let r = getRange s

    match s with
    | SAtom { Token = Symbol name } -> SimpleCase(name, r)
    | SList([ SAtom { Token = Symbol name } ], _) -> SimpleCase(name, r)
    | SList(SAtom { Token = Symbol name } :: tTypes, _) -> DataCase(name, List.map parseType tTypes, r)
    | _ ->
        printfn $"%A{s}"
        failwithf $"Invalid union case at line %d{r.Start.Line}"

let parseRecordField (s: SExpr) : RecordField =
    let r = getRange s

    match s with
    | SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) ->
        { Name = name
          Type = parseType tType
          Range = r }
    | _ -> failwithf $"Invalid record field at line %d{r.Start.Line}"

let parseTypeDefHead (head: SExpr) : string * string list =
    match head with
    | SAtom { Token = Symbol name } -> name, []
    | SList(SAtom { Token = Symbol name } :: args, _) ->
        let parseTypeArg = function
            | SAtom { Token = QuotedSymbol ta } -> ta
            | SAtom { Token = Symbol s } -> s // Just in case they are not quoted
            | _ -> failwithf $"Invalid type argument at line %d{(getRange head).Start.Line}"
        name, List.map parseTypeArg args
    | _ -> failwithf $"Invalid type definition head at line %d{(getRange head).Start.Line}"

let parseTypeDef (s: SExpr) : TypeDef =
    let r = getRange s

    match s with
    | SList([ SAtom { Token = Colon }
              head
              SList(SAtom { Token = Symbol(("Record" | "Struct") as kind) } :: fields, _) ],
            _) ->
        let name, typeArgs = parseTypeDefHead head
        { Name = name
          TypeArgs = typeArgs
          Kind = Record(List.map parseRecordField fields, kind = "Struct")
          Range = r }
    // `Union`, `Enum`, and `Sum` are accepted tags for sum types.
    | SList([ SAtom { Token = Colon }
              head
              SList(SAtom { Token = Symbol("Union" | "Enum" | "Sum") } :: cases, _) ],
            _) ->
        let name, typeArgs = parseTypeDefHead head
        { Name = name
          TypeArgs = typeArgs
          Kind = Union(List.map parseUnionCase cases)
          Range = r }
    // Explicit Alias: (: head (Alias aliasType))
    | SList([ SAtom { Token = Colon }
              head
              SList([ SAtom { Token = Symbol "Alias" }; aliasType ], _) ],
            _) ->
        let name, typeArgs = parseTypeDefHead head
        { Name = name
          TypeArgs = typeArgs
          Kind = Alias(parseType aliasType)
          Range = r }
    // Implicit Alias: (: head aliasType)
    | SList([ SAtom { Token = Colon }; head; aliasType ], _) ->
        let name, typeArgs = parseTypeDefHead head
        { Name = name
          TypeArgs = typeArgs
          Kind = Alias(parseType aliasType)
          Range = r }
    | _ -> failwithf $"Invalid type definition at line %d{r.Start.Line}"

let parseDefunArg (arg: SExpr) : (string * FType option) =
    match arg with
    | SAtom { Token = Symbol n } -> (n, None)
    | SList([ SAtom { Token = Colon }; SAtom { Token = Symbol n }; t ], _) -> (n, Some(parseType t))
    | _ -> failwith "Invalid defun argument"

let parseDefunArgs (args: SExpr list) : (string * FType option) list = args |> List.map parseDefunArg

let parseDefunRest (rest: SExpr list) : (FType option * SExpr list) =
    match rest with
    | SAtom { Token = Colon } :: t :: body -> (Some(parseType t), body)
    | body -> (None, body)


// Desugar a quoted list '(1 2 3) into (Cons 1 (Cons 2 (Cons 3 Nil)))
// Nested lists are recursively quoted: '(1 (2 3)) → (Cons 1 (Cons (Cons 2 (Cons 3 Nil)) Nil))
// Dotted pairs (a . b) within quoted lists become tuples
let desugarQuotedList (items: SExpr list) (r: Range) : Expr =
    let rec quoteItem (s: SExpr) : Expr =
        let ir = getRange s
        match s with
        | SAtom { Token = NumberLit n } -> EInt(n, ir)
        | SAtom { Token = StringLit str } -> EString(str, ir)
        | SAtom { Token = Symbol sym } -> EIdent(sym, ir)
        | SAtom { Token = QuotedSymbol sym } -> EQuotedSymbol(sym, ir)
        // Nested list → recursive Cons chain
        | SList(SAtom { Token = Symbol "Tuple" } :: tupleItems, _) ->
            // Dotted pair in a quoted list: '(a . b) → (Tuple a b)
            ETuple(List.map quoteItem tupleItems, ir)
        | SList(inner, _) ->
            buildConsChain inner ir
        | _ -> failwithf $"Unsupported item in quoted list at line %d{ir.Start.Line}"
    and buildConsChain (items: SExpr list) (r: Range) : Expr =
        match items with
        | [] -> EIdent("Nil", r)
        | item :: rest ->
            let hd = quoteItem item
            let tl = buildConsChain rest r
            EApp(EIdent("Cons", r), [hd; tl], r)
    buildConsChain items r

/// An expression's own range.
let exprRange (e: Expr) : Range =
    match e with
    | EInt(_, r)
    | EString(_, r)
    | EQuotedSymbol(_, r)
    | EKeyword(_, r)
    | EIdent(_, r)
    | ETuple(_, r)
    | EApp(_, _, r)
    | ECast(_, _, r)
    | ELet(_, _, _, _, _, _, r)
    | ELetMono(_, _, _, r)
    | ELetRec(_, _, r)
    | ELetTuple(_, _, _, r)
    | ELetMutable(_, _, _, _, r)
    | ESet(_, _, r)
    | EIf(_, _, _, r)
    | EWhen(_, _, _, r)
    | EFun(_, _, r)
    | ERecord(_, r)
    | ERecordUpdate(_, _, r)
    | EGetField(_, _, r)
    | EList(_, r)
    | EVec(_, r)
    | EMatch(_, _, r)
    | ETryFinally(_, _, r)
    | ESeq(_, r)
    | EYield(_, r)
    | EYieldFrom(_, r) -> r

/// Every expression held directly inside `e`.
///
/// Exhaustive on purpose: this is used to refuse a loop name outside tail
/// position, and a case missed here would let one through to a much worse
/// diagnostic later.
let exprChildren (e: Expr) : Expr list =
    match e with
    | EInt _
    | EString _
    | EQuotedSymbol _
    | EKeyword _
    | EIdent _ -> []
    | ECast(_, x, _)
    | EGetField(x, _, _)
    | ESeq(x, _)
    | EYield(x, _)
    | EYieldFrom(x, _) -> [ x ]
    | ESet(_, x, _) -> [ x ]
    | ETuple(xs, _)
    | EList(xs, _)
    | EVec(xs, _) -> xs
    | EApp(f, args, _) -> f :: args
    | ELet(_, _, _, _, v, b, _) -> [ v; b ]
    | ELetMono(_, v, b, _) -> [ v; b ]
    | ELetTuple(_, v, b, _) -> [ v; b ]
    | ELetMutable(_, _, v, b, _) -> [ v; b ]
    | ELetRec(bindings, b, _) -> (bindings |> List.map (fun (_, _, _, _, v) -> v)) @ [ b ]
    | EIf(c, t, f, _) -> [ c; t; f ]
    | EWhen(c, b, _, _) -> [ c; b ]
    | EFun(_, b, _) -> [ b ]
    | ERecord(fields, _) -> fields |> List.map snd
    | ERecordUpdate(_, fields, _) -> fields |> List.map snd
    | ETryFinally(b, c, _) -> [ b; c ]
    | EMatch(target, clauses, _) ->
        target
        :: (clauses |> List.collect (fun (_, guard, body) -> (Option.toList guard) @ [ body ]))

/// One clause of a `(loop ...)`, still unparsed.
///
/// The clause list is flat and there is no body position: every clause carries
/// its own condition, and iteration order is clause order.
type private LoopClause =
    | LFor of SExpr * SExpr * Range
    | LLet of SExpr * SExpr * Range
    | LDo of SExpr list * Range
    | LWhen of SExpr * Range
    | LSubloop of Range
    /// `(:acc name (collector args...) #:when cond)`. The `#:when` is a clause
    /// modifier the loop form intercepts, never something the collector sees: it
    /// mentions loop variables, and construction arguments are hoisted out of
    /// the loop entirely.
    | LAcc of string * SExpr * SExpr option * Range
    /// Ends the whole loop when the condition holds, before the rest of the
    /// iteration runs. Routes through the finish block like every other exit.
    | LBreak of SExpr * Range
    /// Abandons the current subloop and resumes the enclosing level's next
    /// iteration — an early return from a subloop, not an iteration skip. The
    /// same edge inner exhaustion takes.
    | LEndSubloop of SExpr * Range
    /// Ends the loop *after* the current iteration completes.
    ///
    /// Not a mechanism of its own: it is a `:break` on a hidden accumulator
    /// holding the previous iteration's verdict, and the two sit at the position
    /// `:final` occupied with the break first. An accumulator slot read at the
    /// top of iteration N holds what was written at the end of N-1, which is
    /// exactly "finish this one, then stop". Reversed, the break would read the
    /// value written this iteration and `:final` would collapse into `:break`.
    | LFinal of SExpr * Range

/// An accumulator's slot, after its collector form has been split.
type private AccSlot =
    { /// Prologue binding holding the collector value.
      Collector: string
      /// The slot's name. A user accumulator keeps the name it was declared
      /// with — it is in scope through the loop, and each `:acc` rebinds it, so
      /// a later clause reads the value as of its own position.
      Name: string
      CollectorExpr: Expr
      StepForm: SExpr
      Modifier: SExpr option
      /// `:final`'s accumulator, which is not the author's and must not appear
      /// in the finish block's result.
      Hidden: bool
      /// The level whose body steps it. Every accumulator is a slot on *every*
      /// member — they are hoisted — but only one level runs its step.
      Level: int
      Range: Range }

/// A `(loop ...)` clause's own range, for diagnostics.
let private loopClauseRange (c: LoopClause) : Range =
    match c with
    | LFor(_, _, r)
    | LLet(_, _, r)
    | LDo(_, r)
    | LWhen(_, r)
    | LSubloop r
    | LAcc(_, _, _, r)
    | LBreak(_, r)
    | LEndSubloop(_, r)
    | LFinal(_, r) -> r

let rec parseExpr (s: SExpr) : Expr =
    let r = getRange s

    let rec processArgs items =
        match items with
        | [] -> []
        | SAtom { Token = Comma } :: rest -> processArgs rest
        | item :: rest -> parseExpr item :: processArgs rest

    // Treat specific operator tokens as valid identifiers in expressions
    let (|Ident|_|) =
        function
        | SAtom { Token = Symbol "#t" } -> Some "true"
        | SAtom { Token = Symbol "#f" } -> Some "false"
        | SAtom { Token = Symbol sym } -> Some sym
        | _ -> None

    match s with
    | SAtom { Token = NumberLit n } -> EInt(n, r)
    | SAtom { Token = StringLit str } -> EString(str, r)
    | SAtom { Token = QuotedSymbol sym } -> EQuotedSymbol(sym, r)
    | SAtom { Token = Keyword sym } -> EKeyword(sym, r)
    | Ident sym -> EIdent(sym, r)

    | SList(head :: args, listRange) ->
        match head with
        | Ident sym ->
            match sym with
            | "cast" ->
                match args with
                | [ typeSExpr; valSExpr ] ->
                    ECast(parseType typeSExpr, parseExpr valSExpr, r)
                | _ -> failwithf $"Invalid cast syntax at line %d{r.Start.Line}. Expected: (cast <type> <expr>)"
            | "let" ->
                match args with
                | SList(bindings, _) :: bodyExprs ->
                    let body = parseBody bodyExprs listRange

                    List.foldBack
                        (fun bind acc ->
                            match bind with
                            | SList([ Ident k; v ], _) -> ELet(k, false, [], None, parseExpr v, acc, getRange bind)
                            | _ -> failwith "Invalid let binding")
                        bindings
                        body
                | Ident name :: SList(bindings, _) :: bodyExprs ->
                    // Named let
                    let parsedBindings =
                        bindings
                        |> List.map (function
                            | SList([ Ident k; v ], _) -> (k, parseExpr v)
                            | _ -> failwith "Invalid named let binding")
                    
                    let argNames = parsedBindings |> List.map fst
                    let argVals = parsedBindings |> List.map snd
                    let body = parseBody bodyExprs listRange
                    let funcBinding = (name, true, argNames, None, body)
                    ELetRec([funcBinding], EApp(EIdent(name, r), argVals, r), r)
                | _ -> failwith "Invalid let syntax"

            // Internal: the readable form of `ELetMono`, so that an inline
            // template containing one survives export and re-import. Written by
            // desugarings and by `serializeExpr`, not intended to be hand-written.
            | "let/mono" ->
                match args with
                | [ Ident name; value; body ] -> ELetMono(name, parseExpr value, parseExpr body, listRange)
                | _ ->
                    failwithf $"Invalid let/mono syntax at line %d{r.Start.Line}. Expected: (let/mono name value body)"

            | "letrec" ->
                match args with
                | SList(bindings, _) :: bodyExprs ->
                    let parsedBindings =
                        bindings
                        |> List.map (function
                            // Standard explicit letrec assumes value bindings or manually desugared lambdas
                            | SList([ Ident k; v ], _) -> (k, false, [], None, parseExpr v)
                            | _ -> failwith "Invalid letrec binding")

                    ELetRec(parsedBindings, parseBody bodyExprs listRange, r)
                | _ -> failwith "Invalid letrec syntax"
            | "set!" ->
                match args with
                | [ Ident target; valExpr ] -> ESet(target, parseExpr valExpr, r)
                | _ -> failwithf $"Invalid set! syntax at line %d{r.Start.Line}. Expected: (set! name value)"
            | "->" ->
                match args with
                | init :: steps ->
                    let rec buildThread (prev: SExpr) (step: SExpr) : SExpr =
                        match step with
                        | SAtom { Token = Symbol _ } as sym ->
                            SList([sym; prev], getRange sym)
                        | SList(items, stepR) ->
                            let rec replaceListItems (items: SExpr list) : SExpr list * bool =
                                match items with
                                | [] -> [], false
                                | SAtom { Token = Hash } as h :: SList(subItems, subR) :: tail ->
                                    let rest, foundInRest = replaceListItems tail
                                    h :: SList(subItems, subR) :: rest, foundInRest
                                | head :: tail ->
                                    let newHead, foundHead = replaceAmpersand head
                                    let newTail, foundTail = replaceListItems tail
                                    newHead :: newTail, foundHead || foundTail

                            and replaceAmpersand (expr: SExpr) : SExpr * bool =
                                match expr with
                                | SAtom { Token = Symbol "&" } -> prev, true
                                | SList(subItems, subR) ->
                                    let newItems, found = replaceListItems subItems
                                    SList(newItems, subR), found
                                | _ -> expr, false
                            
                            let newItems, hasAmp = replaceListItems items
                            if hasAmp then
                                SList(newItems, stepR)
                            else
                                match items with
                                | head :: tail -> SList(head :: prev :: tail, stepR)
                                | [] -> failwithf $"Invalid empty list in -> macro at line %d{stepR.Start.Line}"
                        | _ -> failwithf $"Invalid step in -> macro at line %d{(getRange step).Start.Line}"

                    let threadExpr = steps |> List.fold buildThread init
                    parseExpr threadExpr
                | _ -> failwithf $"-> requires at least one argument at line %d{r.Start.Line}"
            | "if" ->
                match args with
                | [ cond; t; f ] -> EIf(parseExpr cond, parseExpr t, parseExpr f, r)
                | _ -> failwith "Invalid if syntax"

            // `when` and `unless` are one-armed: there is no second branch for
            // the body's type to agree with, so they are statements rather than
            // expressions. Desugaring them into `if` with an empty tuple as the
            // missing arm made every body that was not itself an empty tuple a
            // type error — which is to say every body anyone would write.
            | "when" ->
                match args with
                | cond :: bodyExprs when not bodyExprs.IsEmpty ->
                    EWhen(parseExpr cond, parseBody bodyExprs listRange, false, listRange)
                | _ -> failwithf $"Invalid when syntax at line %d{r.Start.Line}. Expected: (when cond body...)"

            | "unless" ->
                match args with
                | cond :: bodyExprs when not bodyExprs.IsEmpty ->
                    EWhen(parseExpr cond, parseBody bodyExprs listRange, true, listRange)
                | _ -> failwithf $"Invalid unless syntax at line %d{r.Start.Line}. Expected: (unless cond body...)"

            // A `seq` body is a block like any other, but it is *not* run where
            // it is written: the form evaluates to a sequence, and the body runs
            // a `yield` at a time as that sequence is consumed.
            | "seq" ->
                match args with
                | [] -> failwithf $"Invalid seq syntax at line %d{r.Start.Line}. Expected: (seq body...)"
                | bodyExprs -> ESeq(parseBody bodyExprs listRange, listRange)

            // A monadic block. `(seq ...)` was already taken by lazy sequences,
            // so the form is spelled `do`.
            //
            //   (do (:bind x xs)
            //       (:let  y (+ x 1))
            //       (:then (side-effecting-action))
            //       (:return (* y 2)))
            //
            // The last form may be *any* `m a`, not necessarily `:return`:
            // otherwise a monadic loop could not be written at all, because the
            // recursive call has to *be* the result rather than be wrapped in a
            // `pure`. `(:return e)` is sugar for `(pure e)` in tail position.
            | "do" ->
                match args with
                | [] -> failwithf $"Invalid do syntax at line %d{r.Start.Line}. Expected: (do form...)"
                | forms -> desugarDo forms listRange

            // Guarded rather than claimed outright: `(loop (+ i 1))` is how a
            // named `let` recurses, and that must keep meaning a call. A clause
            // is a keyword-headed list, which an argument expression is not.
            | "loop" when isLoopForm args -> desugarLoop args listRange

            | "yield" ->
                match args with
                | [ value ] -> EYield(parseExpr value, listRange)
                | _ -> failwithf $"Invalid yield syntax at line %d{r.Start.Line}. Expected: (yield value)"

            | "yield-from" ->
                match args with
                | [ source ] -> EYieldFrom(parseExpr source, listRange)
                | _ -> failwithf $"Invalid yield-from syntax at line %d{r.Start.Line}. Expected: (yield-from seq)"

            | "and" ->
                let rec buildAnd items =
                    match items with
                    | [] -> EIdent("true", listRange)
                    | [last] -> parseExpr last
                    | current :: rest -> 
                        EIf(parseExpr current, buildAnd rest, EIdent("false", listRange), listRange)
                buildAnd args

            | "or" ->
                let rec buildOr items =
                    match items with
                    | [] -> EIdent("false", listRange)
                    | [last] -> parseExpr last
                    | current :: rest ->
                        EIf(parseExpr current, EIdent("true", listRange), buildOr rest, listRange)
                buildOr args

            | "not" ->
                match args with
                | [arg] -> EIf(parseExpr arg, EIdent("false", listRange), EIdent("true", listRange), listRange)
                | _ -> failwithf $"Invalid not syntax at line %d{r.Start.Line}"

            | "fun" ->
                match args with
                | SList(fargs, _) :: bodyExprs ->
                    let argNames =
                        fargs
                        |> List.choose (function
                            | Ident n -> Some n
                            | SAtom { Token = Comma } -> None
                            | _ -> failwith "Expected arg name")

                    EFun(argNames, parseBody bodyExprs listRange, r)
                | _ -> failwith "Invalid fun syntax"

            | "match" ->
                match args with
                | targetExpr :: clauses ->
                    let target = parseExpr targetExpr

                    let parsedClauses =
                        clauses
                        |> List.map (fun clause ->
                            let rClause = getRange clause

                            match clause with
                            // Clause with a guard: (pattern #:when guard body...)
                            | SList(pattern :: SAtom { Token = Keyword "when" } :: guard :: bodyExprs, _) ->
                                (parsePattern pattern, Some(parseExpr guard), parseBody bodyExprs rClause)
                            // Standard clause: (pattern body...)
                            | SList(pattern :: bodyExprs, _) ->
                                (parsePattern pattern, None, parseBody bodyExprs rClause)
                            | _ -> failwithf $"Invalid match clause at line %d{rClause.Start.Line}")

                    EMatch(target, parsedClauses, r)
                | _ -> failwithf $"Invalid match syntax at line %d{r.Start.Line}"

            // `struct*` forms are accepted synonyms for the `record*` forms.
            | "record" | "struct" ->
                let fields =
                    args
                    |> List.map (function
                        | SList([ Ident k; v ], _) -> (k, parseExpr v)
                        | bad ->
                            failwithf
                                $"Invalid %s{sym} field at line %d{(getRange bad).Start.Line}: expected (field-name value)")

                ERecord(fields, r)

            | "record-set" | "struct-set" ->
                match args with
                | Ident baseRec :: fields ->
                    let parsedFields =
                        fields
                        |> List.map (function
                            | SList([ Ident k; v ], _) -> (k, parseExpr v)
                            | bad ->
                                failwithf
                                    $"Invalid %s{sym} field at line %d{(getRange bad).Start.Line}: expected (field-name value)")

                    ERecordUpdate(baseRec, parsedFields, r)
                | _ -> failwithf $"Invalid %s{sym} syntax at line %d{r.Start.Line}: expected (%s{sym} target (field value) ...)"
            
            | "record-get" | "struct-get" ->
                match args with
                | [ target; Ident field ] ->
                    EGetField(parseExpr target, field, r)
                | _ -> failwithf $"Invalid %s{sym} syntax at line %d{r.Start.Line}: expected (%s{sym} target field-name)"

            | "Tuple" -> ETuple(processArgs args, listRange)

            // Quoted list literal: '(1 2 3) → Cons chain
            | "quoted-list" -> desugarQuotedList args listRange

            // Vec literal: [1 2 3] → EVec
            | "vec-literal" -> EVec(processArgs args, listRange)

            // Standard function application
            | _ -> EApp(EIdent(sym, getRange head), processArgs args, listRange)


        | _ ->
            // Fallback for tuples or unquoted lists
            EApp(parseExpr head, processArgs args, listRange)

    | SList([], listRange) -> ETuple([], listRange)

    // Explicit token catches for better debugging
    | SAtom { Token = Comma } -> failwithf $"Unexpected comma at line %d{r.Start.Line}"
    | SAtom { Token = Quote } -> failwithf $"Unexpected quote at line %d{r.Start.Line}"
    | _ -> failwithf $"Unexpected expression at line %d{r.Start.Line}"

/// Desugars a `(do ...)` block into `bind` / `pure`.
///
/// Each generated `bind` carries the range of *its own* form. Giving them all
/// the range of the opening paren made every type error in a ten-step block
/// point at the same character.
and desugarDo (forms: SExpr list) (fallbackRange: Range) : Expr =
    let named (s: SExpr) =
        match s with
        | SList(SAtom { Token = Keyword k } :: rest, r) -> Some(k, rest, r)
        | _ -> None

    match forms with
    | [] -> failwithf $"Invalid do syntax at line %d{fallbackRange.Start.Line}: the block is empty"

    | [ last ] ->
        match named last with
        | Some("return", [ e ], r) -> EApp(EIdent("pure", r), [ parseExpr e ], r)
        | Some("return", _, r) -> failwithf $"Invalid (:return ...) at line %d{r.Start.Line}. Expected: (:return expr)"
        | Some(("bind" | "let" | "then") as k, _, r) ->
            failwithf
                $"A (do ...) block cannot end with (:%s{k} ...) at line %d{r.Start.Line}. Its last form is the block's value."
        // Any `m a` may be the last form, which is what lets a monadic loop put
        // its own recursive call in tail position.
        | _ -> parseExpr last

    | first :: rest ->
        let continuation () = desugarDo rest fallbackRange

        match named first with
        // `:bind` takes an identifier, deliberately. A pattern would force the
        // failure question — what `(:bind (Some x) e)` means when the match
        // fails — which wants `MonadFail` rather than a match that can throw.
        | Some("bind", [ SAtom { Token = Symbol name }; e ], r) ->
            EApp(EIdent("bind", r), [ parseExpr e; EFun([ name ], continuation (), r) ], r)
        | Some("bind", _, r) ->
            failwithf $"Invalid (:bind ...) at line %d{r.Start.Line}. Expected: (:bind name expr) — a plain identifier, not a pattern."

        | Some("let", [ SAtom { Token = Symbol name }; e ], r) ->
            ELet(name, false, [], None, parseExpr e, continuation (), r)
        | Some("let", _, r) -> failwithf $"Invalid (:let ...) at line %d{r.Start.Line}. Expected: (:let name expr)"

        // `>>`, and named for what it is. Calling it `:do` would invite reading
        // it as a variable-less `:bind`, which in a strict language it is not:
        // on `List`, `>>` multiplies out the elements it discards.
        | Some("then", [ e ], r) ->
            EApp(EIdent("bind", r), [ parseExpr e; EFun([ "_" ], continuation (), r) ], r)
        | Some("then", _, r) -> failwithf $"Invalid (:then ...) at line %d{r.Start.Line}. Expected: (:then expr)"

        | Some("return", _, r) ->
            failwithf $"(:return ...) at line %d{r.Start.Line} must be the last form of its (do ...) block."

        | Some(k, _, r) -> failwithf $"Unknown (do ...) form ':%s{k}' at line %d{r.Start.Line}"

        // A plain form in non-tail position is an ordinary statement, run for
        // its effect. It is *not* a variable-less bind.
        | None -> ELet("_", false, [], None, parseExpr first, continuation (), getRange first)

// ---------------------------------------------------------------------------
// (loop ...)
// ---------------------------------------------------------------------------

/// Whether `(loop ...)` is the loop facility rather than a call to something
/// named `loop`.
///
/// `(let loop ((i 0)) ... (loop (+ i 1)))` is how every named `let` in the
/// language recurses, so the head symbol cannot be claimed outright. A clause is
/// a keyword-headed list and an argument expression is not, which tells the two
/// apart without reserving the name.
and private isLoopForm (args: SExpr list) : bool =
    match args with
    | SList(SAtom { Token = Keyword _ } :: _, _) :: _ -> true
    // A named loop puts its name first, so the clause is one further along.
    // `(loop f (g 1))` — a call to a named `let` taking a function and an
    // argument — still is not one, because `(g 1)` is not keyword-headed.
    | SAtom { Token = Symbol _ } :: SList(SAtom { Token = Keyword _ } :: _, _) :: _ -> true
    | _ -> false

/// Reads one clause. Nothing is desugared here.
and private parseLoopClause (s: SExpr) : LoopClause =
    match s with
    | SList(SAtom { Token = Keyword "for" } :: rest, r) ->
        match rest with
        | [ pat; sequence ] -> LFor(pat, sequence, r)
        | _ -> failwithf $"Invalid (:for ...) at line %d{r.Start.Line}. Expected: (:for pattern sequence)"

    | SList(SAtom { Token = Keyword "let" } :: rest, r) ->
        match rest with
        | [ pat; value ] -> LLet(pat, value, r)
        | _ -> failwithf $"Invalid (:let ...) at line %d{r.Start.Line}. Expected: (:let pattern expr)"

    | SList(SAtom { Token = Keyword "do" } :: rest, r) ->
        if rest.IsEmpty then
            failwithf $"Invalid (:do ...) at line %d{r.Start.Line}. Expected: (:do expr ...)"

        LDo(rest, r)

    | SList(SAtom { Token = Keyword "when" } :: rest, r) ->
        match rest with
        | [ cond ] -> LWhen(cond, r)
        | _ -> failwithf $"Invalid (:when ...) at line %d{r.Start.Line}. Expected: (:when cond)"

    | SList([ SAtom { Token = Keyword "subloop" } ], r) -> LSubloop r

    | SList(SAtom { Token = Keyword "end-subloop-if" } :: rest, r) ->
        match rest with
        | [ cond ] -> LEndSubloop(cond, r)
        | _ ->
            failwithf $"Invalid (:end-subloop-if ...) at line %d{r.Start.Line}. Expected: (:end-subloop-if cond)"

    | SList(SAtom { Token = Keyword "acc" } :: SAtom { Token = Symbol name } :: collector :: rest, r) ->
        let modifier =
            match rest with
            | [] -> None
            | [ SAtom { Token = Keyword "when" }; cond ] -> Some cond
            | _ ->
                failwithf
                    $"Invalid (:acc ...) at line %d{r.Start.Line}. Expected: (:acc name (collector ...) [#:when cond])"

        LAcc(name, collector, modifier, r)

    | SList(SAtom { Token = Keyword "acc" } :: _, r) ->
        failwithf $"Invalid (:acc ...) at line %d{r.Start.Line}. Expected: (:acc name (collector ...) [#:when cond])"

    // Both take a condition rather than being guarded by a preceding `:when`:
    // clauses do not compose, so there is no bare `(:break)` to be reached
    // conditionally.
    | SList(SAtom { Token = Keyword "break" } :: rest, r) ->
        match rest with
        | [ cond ] -> LBreak(cond, r)
        | _ -> failwithf $"Invalid (:break ...) at line %d{r.Start.Line}. Expected: (:break cond)"

    | SList(SAtom { Token = Keyword "final" } :: rest, r) ->
        match rest with
        | [ cond ] -> LFinal(cond, r)
        | _ -> failwithf $"Invalid (:final ...) at line %d{r.Start.Line}. Expected: (:final cond)"

    | SList(SAtom { Token = Keyword k } :: _, r) ->
        failwithf $"Unknown (loop ...) clause ':%s{k}' at line %d{r.Start.Line}"

    | _ ->
        let r = getRange s
        failwithf $"Expected a (loop ...) clause at line %d{r.Start.Line}, which is a keyword-headed list like (:for x xs)"

/// Binds a `:for` or `:let` pattern.
///
/// The pattern is there to destructure and must always match: it is not a
/// filter, and a pattern that could fail would need somewhere to send the
/// failure. So only the shapes that cannot fail are accepted.
and private bindLoopPattern (pat: SExpr) (value: Expr) (body: Expr) (r: Range) : Expr =
    match pat with
    | SAtom { Token = Symbol name } -> ELet(name, false, [], None, value, body, r)

    | SList(SAtom { Token = Symbol "Tuple" } :: parts, pr) when
        not parts.IsEmpty
        && parts
           |> List.forall (function
               | SAtom { Token = Symbol _ }
               | SAtom { Token = Comma } -> true
               | _ -> false)
        ->
        let names =
            parts
            |> List.choose (function
                | SAtom { Token = Symbol n } -> Some n
                | _ -> None)

        ELetTuple(names, value, body, pr)

    | _ ->
        let pr = getRange pat
        failwithf
            $"Invalid pattern at line %d{pr.Start.Line}: a (loop ...) pattern only destructures and must always match, so it has to be a name or (Tuple a b ...)."

/// Splits a collector form into the collector *value* and the per-iteration
/// step expression.
///
/// The convention: the last positional argument is the step expression, and
/// everything before it — plus every keyword argument — constructs the
/// collector. `(listing b)` is `listing` stepping `b`; `(folding #f test)` is
/// `(folding #f)` stepping `test`.
and private splitCollector (s: SExpr) : Expr * SExpr =
    match s with
    | SList(SAtom { Token = Symbol head } :: args, r) ->
        let rec split positional keywords rest =
            match rest with
            | [] -> List.rev positional, List.rev keywords
            | (SAtom { Token = Keyword _ } as k) :: value :: tl -> split positional ((k, value) :: keywords) tl
            | [ SAtom { Token = Keyword k } ] ->
                failwithf $"Keyword argument '#:%s{k}' at line %d{r.Start.Line} has no value"
            | SAtom { Token = Comma } :: tl -> split positional keywords tl
            | x :: tl -> split (x :: positional) keywords tl

        let positional, keywords = split [] [] args

        match List.rev positional with
        | [] ->
            failwithf
                $"Collector at line %d{r.Start.Line} has no step expression. The last positional argument is what is accumulated each iteration, as in (listing x)."
        | stepForm :: revConstruction ->
            let construction = List.rev revConstruction

            let collector =
                if construction.IsEmpty && keywords.IsEmpty then
                    EIdent(head, r)
                else
                    let kwArgs =
                        keywords |> List.collect (fun (k, v) -> [ parseExpr k; parseExpr v ])

                    EApp(EIdent(head, r), (construction |> List.map parseExpr) @ kwArgs, r)

            collector, stepForm

    | _ ->
        let r = getRange s
        failwithf
            $"Expected a collector at line %d{r.Start.Line}, as in (listing x) or (folding seed expr)"

/// Desugars `(loop clause... [=> expr])`.
///
/// A loop is a left fold with early exit that always delivers a result: every
/// exit runs the same finish block. That is why the accumulators are hoisted —
/// they hold state across the whole loop and have to be visible at the end.
and desugarLoop (allForms: SExpr list) (r: Range) : Expr =
    // An optional name comes first, before any clause.
    let userLoopName, forms =
        match allForms with
        | SAtom { Token = Symbol n } :: rest -> Some n, rest
        | _ -> None, allForms

    // `=> expr`, if present, is the last two forms.
    let clauseForms, finishForm =
        let isArrow =
            function
            | SAtom { Token = Symbol "=>" } -> true
            | _ -> false

        match forms |> List.tryFindIndex isArrow with
        | None -> forms, None
        | Some i when i = forms.Length - 2 -> forms |> List.take i, Some(List.last forms)
        | Some i ->
            let ar = getRange forms[i]
            failwithf $"'=>' at line %d{ar.Start.Line} must be followed by exactly one result expression, at the end of the loop."

    if clauseForms.IsEmpty then
        failwithf $"Invalid loop at line %d{r.Start.Line}: it has no clauses"

    let clauses = clauseForms |> List.map parseLoopClause

    match clauses with
    | LFor _ :: _ -> ()
    | c :: _ ->
        let cr = loopClauseRange c
        failwithf
            $"A loop must begin with a (:for ...) at line %d{cr.Start.Line}: every other clause belongs to the level open at its position, and before the first (:for ...) there is none."
    | [] -> ()

    // Level assignment, in one left-to-right pass. A `:for` preceded by anything
    // other than a `:for` opens a new level; every other clause belongs to the
    // level that was current at its own position — so an `:acc` above an inner
    // `:for`, or a `:let` between a `:subloop` and the `:for` it opens, stays in
    // the enclosing level.
    let levelOf =
        let mutable current = -1
        let mutable prevWasFor = false

        clauses
        |> List.map (fun c ->
            match c with
            | LFor _ ->
                if not prevWasFor then current <- current + 1
                prevWasFor <- true
                current
            | _ ->
                prevWasFor <- false
                current)

    let maxLevel = List.max levelOf

    let call (name: string) (args: Expr list) (cr: Range) = EApp(EIdent(name, cr), args, cr)

    /// The names a `:for` or `:let` pattern binds.
    let patternNames (pat: SExpr) =
        match pat with
        | SAtom { Token = Symbol n } -> [ n ]
        | SList(SAtom { Token = Symbol "Tuple" } :: parts, _) ->
            parts
            |> List.choose (function
                | SAtom { Token = Symbol n } -> Some n
                | _ -> None)
        | _ -> []

    // One member per level, plus the names each of them needs.
    let levels =
        [ for i in 0..maxLevel ->
            let mine = List.zip levelOf clauses |> List.filter (fst >> (=) i) |> List.map snd

            let fors =
                mine
                |> List.choose (function
                    | LFor(p, sq, cr) -> Some(p, sq, cr)
                    | _ -> None)

            // `:subloop` emits nothing. Its only role is to have not been a
            // `:for`, which the pass above has already taken account of.
            let others =
                mine
                |> List.filter (function
                    | LFor _
                    | LSubloop _ -> false
                    | _ -> true)

            let bound =
                mine
                |> List.collect (function
                    | LFor(p, _, _) -> patternNames p
                    | LLet(p, _, _) -> patternNames p
                    | _ -> [])

            {| Index = i
               Fors = fors
               Others = others
               Bound = bound
               SeqNames = fors |> List.map (fun _ -> Gensym.fresh "loopseq")
               CurNames = fors |> List.map (fun _ -> Gensym.fresh "loopcur")
               Member = Gensym.fresh "looplevel" |} ]

    // One slot per accumulator, in declaration order across *every* level: an
    // accumulator is hoisted, lives on all members, and is visible in the finish
    // block. `:final` contributes one of its own: a `folding` seeded with false,
    // whose step is the test.
    let accInfo =
        List.zip levelOf clauses
        |> List.choose (fun (level, clause) ->
            match clause with
            | LAcc(name, collector, modifier, cr) ->
                let collectorExpr, stepForm = splitCollector collector

                Some
                    { Collector = Gensym.fresh "loopcol"
                      Name = name
                      CollectorExpr = collectorExpr
                      StepForm = stepForm
                      Modifier = modifier
                      Hidden = false
                      Level = level
                      Range = cr }

            | LFinal(cond, cr) ->
                Some
                    { Collector = Gensym.fresh "loopcol"
                      // A gensym, so a user accumulator that happens to be
                      // called `tmp` cannot be captured by it.
                      Name = Gensym.fresh "loopfinal"
                      CollectorExpr = call "folding" [ EIdent("false", cr) ] cr
                      StepForm = cond
                      Modifier = None
                      Hidden = true
                      Level = level
                      Range = cr }

            | _ -> None)

    let accNames = accInfo |> List.map (fun slot -> slot.Name)

    /// The slot vector of level `i`, in emission order.
    ///
    /// Every enclosing level's sequences and cursors are carried, because an
    /// inner level has to be able to jump *back* to its parent with the parent's
    /// cursors advanced — and every enclosing level's bindings too, because an
    /// inner sequence or clause may name them and a member is a separate
    /// function with no lexical view of its caller. Accumulators are on every
    /// member: they are hoisted, and the finish block reads them wherever it is
    /// reached from.
    ///
    /// Level 0's sequences are absent by design: they are loop-invariant, so
    /// they sit in the prologue and are lexically in scope for the whole group.
    let slotNames (i: int) : string list =
        [ for j in 0..i do
              if j > 0 then yield! levels[j].SeqNames
              yield! levels[j].CurNames
          for j in 0 .. i - 1 do
              yield! levels[j].Bound
          yield! accNames ]

    /// A jump to level `target`, filling every slot: with `overrides` where one
    /// is given, and with whatever is in scope under that name otherwise.
    ///
    /// A `TRecur` carries one argument per slot, so a partial update has to be
    /// completed here rather than left to the emitter.
    let jump (target: int) (overrides: Map<string, Expr>) (cr: Range) =
        let args =
            slotNames target
            |> List.map (fun n ->
                match Map.tryFind n overrides with
                | Some e -> e
                | None -> EIdent(n, cr))

        EApp(EIdent(levels[target].Member, cr), args, cr)

    /// Level `i`'s cursors, one step on.
    let advanced (i: int) (cr: Range) =
        List.map2
            (fun sn cn -> cn, call "next" [ EIdent(sn, cr); EIdent(cn, cr) ] cr)
            levels[i].SeqNames
            levels[i].CurNames
        |> Map.ofList

    /// The next iteration of level `i`: its own cursors advanced, everything
    /// else as it stands.
    let advanceLevelWith (i: int) (extra: Map<string, Expr>) (cr: Range) =
        let overrides = Map.fold (fun acc k v -> Map.add k v acc) (advanced i cr) extra
        jump i overrides cr

    let advanceLevel (i: int) (cr: Range) = advanceLevelWith i Map.empty cr

    // `done?` exactly once per iteration, in clause order, short-circuiting:
    // when one sequence is done the level is over and no later `done?` runs.
    let exhausted (i: int) =
        let tests =
            List.map2
                (fun sn cn -> call "done?" [ EIdent(sn, r); EIdent(cn, r) ] r)
                levels[i].SeqNames
                levels[i].CurNames

        let rec anyOf ts =
            match ts with
            | [ last ] -> last
            | t :: tl -> EIf(t, EIdent("true", r), anyOf tl, r)
            | [] -> EIdent("false", r)

        anyOf tests

    // Every exit runs this. Each accumulator is rebound to its *finished* value,
    // shadowing the slot, so `=> expr` sees the finished one by name.
    //
    // It is a member of the group rather than something spliced at each exit:
    // exhaustion, every `:break`, every `:final` and a named loop's declining
    // `:do` all reach it, and inlining it at each one would emit as many copies
    // of the `=>` expression as there are ways out.
    let exitName = Gensym.fresh "loopexit"

    let finishBlockBody =
        // `:final`'s accumulator is not the author's and has no business in the
        // result, so only the declared ones are delivered or even finished.
        let declared = accInfo |> List.filter (fun slot -> not slot.Hidden)

        let result =
            match finishForm with
            | Some e -> parseExpr e
            | None ->
                match declared with
                // Nothing to deliver: a loop with no accumulators and no `=>`
                // is pure effect, and types as `void` rather than as unit so
                // that it can be the body of a `void` function. `when` is the
                // language's only void-typed expression form, and with a
                // constant-false condition it is also the emptiest one.
                | [] -> EWhen(EIdent("false", r), ETuple([], r), false, r)
                | [ slot ] -> EIdent(slot.Name, slot.Range)
                | _ -> ETuple(declared |> List.map (fun slot -> EIdent(slot.Name, slot.Range)), r)

        List.foldBack
            (fun slot acc ->
                ELet(
                    slot.Name,
                    false,
                    [],
                    None,
                    call "finish" [ EIdent(slot.Collector, slot.Range); EIdent(slot.Name, slot.Range) ] slot.Range,
                    acc,
                    slot.Range
                ))
            declared
            result

    /// Leaving the loop: hand the accumulators as they stand to the finish
    /// member. They are in scope under their own names at every exit, whether as
    /// a slot or as a rebinding an `:acc` clause made earlier this iteration.
    let finishBlock (cr: Range) =
        EApp(EIdent(exitName, cr), accNames |> List.map (fun n -> EIdent(n, cr)), cr)

    /// Steps one accumulator, then carries on.
    let stepAcc (slot: AccSlot) (rest: Expr) =
        let cr = slot.Range

        let stepped =
            call "step" [ EIdent(slot.Collector, cr); EIdent(slot.Name, cr); parseExpr slot.StepForm ] cr

        let value =
            match slot.Modifier with
            | None -> stepped
            | Some cond -> EIf(parseExpr cond, stepped, EIdent(slot.Name, cr), cr)

        ELet(slot.Name, false, [], None, value, rest, cr)

    /// Entering level `i` from its parent: its sequences are evaluated *here*,
    /// because an inner sequence usually names an outer loop variable and so is
    /// not loop-invariant; its cursors are freshly started from them.
    ///
    /// The sequences are bound to temporaries first — the jump needs their
    /// values, and `start` needs them too, so evaluating the expression twice
    /// would be both wrong and slow.
    let enterLevel (i: int) (cr: Range) =
        let temps = levels[i].Fors |> List.map (fun _ -> Gensym.fresh "loopenter")

        let overrides =
            (List.map2 (fun sn t -> sn, EIdent(t, cr)) levels[i].SeqNames temps)
            @ (List.map2 (fun cn t -> cn, call "start" [ EIdent(t, cr) ] cr) levels[i].CurNames temps)
            |> Map.ofList

        List.foldBack
            (fun (t, (_, sequence, fr)) acc -> ELetMono(t, parseExpr sequence, acc, fr))
            (List.zip temps levels[i].Fors)
            (jump i overrides cr)

    /// Leaving level `i`: level 0 is the end of the loop, and any other level
    /// hands back to its parent with the parent's cursors advanced — the same
    /// edge an `:end-subloop-if` takes.
    let exitLevel (i: int) (cr: Range) =
        if i = 0 then finishBlock cr else advanceLevel (i - 1) cr

    // The clauses of one level, in order. The last of them falls into the next
    // level if there is one, and otherwise into the next iteration of this one —
    // unless a named loop's final `:do` has taken that edge over.
    let rec buildClauses (level: int) (cs: LoopClause list) (accsLeft: AccSlot list) =
        let continueEdgeOf (cr: Range) =
            if level < maxLevel then enterLevel (level + 1) cr else advanceLevel level cr

        match cs with
        | [] -> continueEdgeOf r

        | LLet(pat, value, cr) :: tl ->
            bindLoopPattern pat (parseExpr value) (buildClauses level tl accsLeft) cr

        // In a named loop the *final* `:do` owns the continue edge: if it tail
        // calls the loop, that is the jump, and if it completes without one the
        // loop leaves through the finish block like any other exit.
        | [ LDo(exprs, cr) ] when userLoopName.IsSome && level = maxLevel ->
            let name = userLoopName.Value
            let statements = exprs |> List.take (exprs.Length - 1)
            let final = List.last exprs

            List.foldBack
                (fun e acc ->
                    let parsed = parseExpr e
                    rejectLoopName name parsed
                    ELet("_", false, [], None, parsed, acc, cr))
                statements
                (continueEdge level name (parseExpr final) cr)

        | LDo(exprs, cr) :: tl ->
            List.foldBack
                (fun e acc -> ELet("_", false, [], None, parseExpr e, acc, cr))
                exprs
                (buildClauses level tl accsLeft)

        // Skips the rest of *this* iteration of *this* level. Clauses above it
        // have already run, so an accumulator stepped before it keeps what it
        // was given.
        | LWhen(cond, cr) :: tl ->
            EIf(parseExpr cond, buildClauses level tl accsLeft, advanceLevel level cr, cr)

        // Abandons this level and resumes the enclosing one — an early return
        // from a subloop, not an iteration skip. At level 0 the two would
        // coincide, which is a coincidence rather than a definition.
        | LEndSubloop(cond, cr) :: tl ->
            if level = 0 then
                failwithf
                    $"(:end-subloop-if ...) at line %d{cr.Start.Line} is at the outermost level, where there is no enclosing loop to resume. Use (:when ...) to skip an iteration, or (:break ...) to leave the loop."

            EIf(parseExpr cond, exitLevel level cr, buildClauses level tl accsLeft, cr)

        // Leaves the whole loop from any level, through the finish block.
        // Accumulators stepped earlier in this iteration keep what they were
        // given.
        | LBreak(cond, cr) :: tl ->
            EIf(parseExpr cond, finishBlock cr, buildClauses level tl accsLeft, cr)

        // `:break` on the hidden accumulator, then the accumulator's own step —
        // in that order. The slot still holds the previous iteration's verdict
        // when the break reads it, which is what makes this "after the current
        // iteration" rather than "before the rest of it".
        | LFinal _ :: tl ->
            match accsLeft with
            | slot :: restAcc ->
                EIf(
                    EIdent(slot.Name, slot.Range),
                    finishBlock slot.Range,
                    stepAcc slot (buildClauses level tl restAcc),
                    slot.Range
                )
            | [] -> failwith "internal error: :final without its accumulator"

        | LAcc _ :: tl ->
            match accsLeft with
            | slot :: restAcc -> stepAcc slot (buildClauses level tl restAcc)
            | [] -> failwith "internal error: accumulator clause without its info"

        | (LFor _ | LSubloop _) :: _ -> failwith "internal error: clause should have been rejected"

    /// Rewrites the tail positions of a named loop's final `:do`.
    ///
    /// Every tail position either *is* a call to the loop — which becomes the
    /// jump, keeping it a tail call so it can be one — or is not, in which case
    /// it runs for its effect and the loop leaves through the finish block.
    and continueEdge (level: int) (name: string) (e: Expr) (cr: Range) : Expr =
        match e with
        | EApp(EIdent(n, ir), args, ar) when n = name ->
            for a in args do
                rejectLoopName name a

            advanceLevelWith level (parseOverrides name args ir) ar

        | EIf(cond, t, f, ir) ->
            rejectLoopName name cond
            EIf(cond, continueEdge level name t cr, continueEdge level name f cr, ir)

        | ELet(n, isFun, args, ann, value, body, ir) ->
            rejectLoopName name value
            ELet(n, isFun, args, ann, value, continueEdge level name body cr, ir)

        | ELetTuple(names, value, body, ir) ->
            rejectLoopName name value
            ELetTuple(names, value, continueEdge level name body cr, ir)

        // Anything else completes, and then the loop is over.
        | other ->
            rejectLoopName name other
            ELet("_", false, [], None, other, finishBlock cr, cr)

    /// `(lp #:name expr ...)` — the slots the call overrides.
    and parseOverrides (name: string) (args: Expr list) (cr: Range) : Map<string, Expr> =
        let rec go acc rest =
            match rest with
            | [] -> acc
            | EKeyword(k, kr) :: value :: tl ->
                if not (List.contains k accNames) then
                    let known =
                        accNames |> List.filter (fun n -> not (n.StartsWith "loopfinal")) |> String.concat ", "

                    let known = if known = "" then "(none)" else known

                    failwithf
                        $"'%s{name}' at line %d{kr.Start.Line} has no slot called '#:%s{k}'. A named loop can override its accumulators — %s{known} — but not a (:for ...) variable, which is derived from its cursor rather than carried."

                go (Map.add k value acc) tl
            | EKeyword(k, kr) :: [] -> failwithf $"'#:%s{k}' at line %d{kr.Start.Line} has no value"
            | other :: _ ->
                let orr = exprRange other
                failwithf
                    $"'%s{name}' at line %d{orr.Start.Line} takes only keyword arguments: write ('%s{name}') to advance everything, or ('%s{name}' #:acc expr) to override one accumulator."

        go Map.empty args

    /// The loop name is a jump target, not a value: it has no lowering anywhere
    /// but tail position, so anything else is refused where it is written.
    and rejectLoopName (name: string) (e: Expr) : unit =
        let rec go (x: Expr) =
            match x with
            | EIdent(n, ir) when n = name ->
                failwithf
                    $"'%s{name}' at line %d{ir.Start.Line} is a loop name, which may only be tail called from the loop's last (:do ...). It is a jump, so it cannot be used as a value or called from anywhere else."
            | _ -> exprChildren x |> List.iter go

        go e

    let bindCurrents (i: int) (inner: Expr) =
        List.foldBack
            (fun ((pat, _, cr), (sn, cn)) acc ->
                bindLoopPattern pat (call "current" [ EIdent(sn, cr); EIdent(cn, cr) ] cr) acc cr)
            (List.zip levels[i].Fors (List.zip levels[i].SeqNames levels[i].CurNames))
            inner

    // One member per level. Every level transition is a tail call by
    // construction, and they are all in one group rather than nested: a jump
    // across levels has to reach the *same* switch, and a nested group would
    // bind it to the wrong one.
    let members =
        levels
        |> List.map (fun lvl ->
            let accsHere = accInfo |> List.filter (fun slot -> slot.Level = lvl.Index)

            let body =
                EIf(
                    exhausted lvl.Index,
                    exitLevel lvl.Index r,
                    bindCurrents lvl.Index (buildClauses lvl.Index lvl.Others accsHere),
                    r
                )

            (lvl.Member, true, slotNames lvl.Index, None, body))

    // The finish member. It calls nothing, so `LetRecify` gives it a component
    // of its own and it is bound ahead of the loop group rather than becoming a
    // case in the same switch — which costs one call on the way out and saves a
    // copy of the block at every other exit.
    let members = members @ [ (exitName, true, accNames, None, finishBlockBody) ]

    let initialArgs =
        (levels[0].SeqNames
         |> List.map (fun sn -> call "start" [ EIdent(sn, r) ] r))
        @ (accInfo |> List.map (fun slot -> call "init" [ EIdent(slot.Collector, slot.Range) ] slot.Range))

    let group =
        ELetRec(members, EApp(EIdent(levels[0].Member, r), initialArgs, r), r)

    // The prologue. Everything loop-invariant is evaluated once, outside: the
    // collectors, and level 0's sequences. An inner level's sequence usually
    // names an outer loop variable, so it is evaluated at the entering jump
    // instead — hoisting is per clause, not unconditional.
    //
    // `let/mono` rather than `let` because a collector is typically a bare
    // nullary constructor, which `let` would generalize — and then its element
    // type would never pin down.
    let withCollectors =
        List.foldBack
            (fun slot acc -> ELetMono(slot.Collector, slot.CollectorExpr, acc, slot.Range))
            accInfo
            group

    List.foldBack
        (fun (sn, (_, sequence, cr)) acc -> ELetMono(sn, parseExpr sequence, acc, cr))
        (List.zip levels[0].SeqNames levels[0].Fors)
        withCollectors

and parseBody (exprs: SExpr list) (fallbackRange: Range) : Expr =
    let rec collectDefs acc remaining =
        match remaining with
        // 1. Standard value definition (def name expr)
        | SList(SAtom { Token = Symbol "def" } :: SAtom { Token = Symbol name } :: [ expr ], _) :: rest ->
            // isFun = false, args = []
            collectDefs ((name, false, [], None, parseExpr expr) :: acc) rest

        // 1b. Annotated value definition (def (: name type) expr)
        | SList(SAtom { Token = Symbol "def" } :: SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) :: [ expr ], _) :: rest ->
            collectDefs ((name, false, [], Some(parseType tType), parseExpr expr) :: acc) rest

        // 2. Local function definition (defun (name args...) body)
        | SList(SAtom { Token = Symbol "defun" } :: SList(SAtom { Token = Symbol name } :: args, _) :: rest, r) :: rest' ->
            let argNames = parseDefunArgs args |> List.map fst
            let _, bodyExprs = parseDefunRest rest
            let fBody = parseBody bodyExprs r
            // isFun = true, args = argNames
            collectDefs ((name, true, argNames, None, fBody) :: acc) rest'

        | _ -> (List.rev acc, remaining)

    and parseItems remaining =
        match remaining with
        | [] -> ETuple([], fallbackRange)

        // 1. Intercept local mutable definitions FIRST
        | SList(SAtom { Token = Symbol "def/mutable" } :: SAtom { Token = Symbol name } :: [ expr ], r) :: rest ->
            ELetMutable(name, None, parseExpr expr, parseItems rest, fallbackRange)

        // Annotated form: (def/mutable (: name type) expr) — the type checker will unify it with the initializer.
        | SList(SAtom { Token = Symbol "def/mutable" } :: SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) :: [ expr ], r) :: rest ->
            ELetMutable(name, Some(parseType tType), parseExpr expr, parseItems rest, fallbackRange)

        // 1c. Local tuple destructuring: (def (a b) expr).
        //
        // Legal at the top level as `DDefTuple`, and it has to be recognized
        // *before* the `def` case below: `collectDefs` does not accept it, and a
        // `def` it does not accept consumes nothing, so the fall-through was an
        // infinite recursion that ended as a stack overflow inside the parser
        // rather than as a diagnostic.
        //
        // `(def (: name type) expr)` also has a list in that position, and is
        // told apart by its head being a colon rather than a name.
        | SList(SAtom { Token = Symbol "def" } :: SList(names, _) :: [ expr ], r) :: rest when
            not names.IsEmpty
            && names
               |> List.forall (function
                   | SAtom { Token = Symbol _ }
                   | SAtom { Token = Comma } -> true
                   | _ -> false)
            ->
            let tupleNames =
                names
                |> List.choose (function
                    | SAtom { Token = Symbol n } -> Some n
                    | _ -> None)

            ELetTuple(tupleNames, parseExpr expr, parseItems rest, r)

        // 2. Starts with def or defun: collect consecutive defs into a letrec block
        | (SList(SAtom { Token = Symbol "def" } :: _, _)) :: _
        | (SList(SAtom { Token = Symbol "defun" } :: _, _)) :: _ ->
            let defs, rest = collectDefs [] remaining

            // Nothing recognized means nothing consumed, and recursing on an
            // unchanged list does not terminate. Whatever shape this is, saying
            // so is the only safe answer.
            if defs.IsEmpty then
                let r = getRange (List.head remaining)

                failwithf
                    $"Invalid def form at line %d{r.Start.Line}. Expected (def name expr), (def (: name type) expr), (def (a b ...) expr) or (defun (name args...) body)."

            ELetRec(defs, parseItems rest, fallbackRange)

        // 3. Single expression left — no sequencing wrapper needed
        | [ expr ] -> parseExpr expr

        // 4. Multiple expressions — sequence them with ELet (isFun = false, empty args)
        | expr :: rest -> ELet("_", false, [], None, parseExpr expr, parseItems rest, fallbackRange)

    parseItems exprs

// New defun arg parser for top-level defuns with keyword/rest support
let rec parseNewDefunArgs (args: SExpr list) : DefunArg list =
    match args with
    | [] -> []
    | SAtom { Token = Symbol n } :: rest -> MandatoryArg n :: parseNewDefunArgs rest
    | SAtom { Token = Comma } :: rest -> parseNewDefunArgs rest
    | SList(SAtom { Token = Keyword name } :: [ defaultExpr ], _) :: rest ->
        KeywordArg(name, parseExpr defaultExpr) :: parseNewDefunArgs rest
    | SAtom { Token = Keyword "rest" } :: SAtom { Token = Symbol name } :: rest ->
        if not rest.IsEmpty then
            failwithf $"Rest argument must be the last argument at line %d{(getRange (List.head rest)).Start.Line}"
        [RestArg name]
    | SAtom { Token = Keyword name } :: defaultExpr :: rest ->
        KeywordArg(name, parseExpr defaultExpr) :: parseNewDefunArgs rest
    | bad :: _ -> failwithf $"Invalid defun argument at line %d{(getRange bad).Start.Line}"

let rec parseDecl (s: SExpr) : Decl =
    let r = getRange s

    match s with
    | SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) ->
        DSignature(name, parseType tType, [], r)
    // (: name type (where (TraitName %var) ...)) — signature with trait constraints
    | SList(SAtom { Token = Colon } :: SAtom { Token = Symbol name } :: tType :: SList(SAtom { Token = Symbol "where" } :: constraintExprs, _) :: _, _) ->
        let constraints =
            constraintExprs |> List.choose (function
                | SList([ SAtom { Token = Symbol traitName }; SAtom { Token = QuotedSymbol varName } ], _) ->
                    Some (traitName, "'" + varName)
                | SList([ SAtom { Token = Symbol traitName }; SAtom { Token = Symbol varName } ], _) ->
                    Some (traitName, varName)
                | _ -> None)
        DSignature(name, parseType tType, constraints, r)

    | SList(SAtom { Token = Symbol "import" } :: imports, _) ->
        // Parse paths like (io readline) into ["io"; "readline"]
        let parseImportPath =
            function
            | SAtom { Token = StringLit s } -> RelativePath s
            | SList(pathNodes, _) ->
                pathNodes
                |> List.map (function
                    | SAtom { Token = Symbol p } -> p
                    | _ -> failwithf $"Invalid import path element at line %d{r.Start.Line}")
                |> ModulePath
            | _ -> failwithf $"Invalid import syntax at line %d{r.Start.Line}"

        DImport(List.map parseImportPath imports, r)

    | SList(SAtom { Token = Symbol "export" } :: exports, _) ->
        // Parse items like poop-on-you
        let exportNames =
            exports
            |> List.map (function
                | SAtom { Token = Symbol e } -> e
                | _ -> failwithf $"Invalid export item at line %d{r.Start.Line}")

        DExport(exportNames, r)

    | SList(SAtom { Token = Symbol "re-export" } :: reExports, _) ->
        let reExportNames =
            reExports
            |> List.map (function
                | SAtom { Token = Symbol e } -> e
                | _ -> failwithf $"Invalid re-export item at line %d{r.Start.Line}")

        DReExport(reExportNames, r)

    | SList(SAtom { Token = Symbol "module" } :: SAtom { Token = Symbol name } :: body, _) ->
        DModule(name, List.map parseDecl body, r)

    | SList(SAtom { Token = Symbol "def" } :: SAtom { Token = Symbol name } :: [ expr ], _) ->
        DDef(name, parseExpr expr, r)

    | SList(SAtom { Token = Symbol "def" } :: SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) :: [ expr ], _) ->
        DDef(name, parseExpr expr, r)

    | SList(SAtom { Token = Symbol "def" } :: SList(names, _) :: [ expr ], _) ->
        let tupleNames =
            names
            |> List.map (function
                | SAtom { Token = Symbol n } -> n
                | SAtom { Token = Comma } -> ""
                | _ -> failwith "Invalid tuple def")
            |> List.filter ((<>) "")

        DDefTuple(tupleNames, parseExpr expr, r)

    | SList(SAtom { Token = Symbol "def/mutable" } :: SAtom { Token = Symbol name } :: [ expr ], _) ->
        DDefMutable(name, parseExpr expr, r)

    | SList(SAtom { Token = Symbol "def/mutable" } :: SList([ SAtom { Token = Colon }; SAtom { Token = Symbol name }; tType ], _) :: [ expr ], _) ->
        DDefMutable(name, parseExpr expr, r)

    | SList(SAtom { Token = Symbol "defun" } :: SList(SAtom { Token = Symbol name } :: args, _) :: rest, _) ->
        let parsedArgs = parseNewDefunArgs args
        // Skip optional inline return type annotation (backward compat, ignored — type comes from signature)
        let bodyExprs =
            match rest with
            | SAtom { Token = Colon } :: _ :: body -> body
            | body -> body
        DDefun(name, parsedArgs, parseBody bodyExprs r, r)
    | SList(SAtom { Token = Symbol "type" } :: typeDefs, _) -> DType(List.map parseTypeDef typeDefs, r)

    | SList(SAtom { Token = Symbol "type-rec" } :: typeDefs, _) -> DTypeRec(List.map parseTypeDef typeDefs, r)

    | SList (SAtom { Token = Symbol "def/trait" } ::
             SList (SAtom { Token = Symbol traitName } :: [ implementorSpec ], _) ::
             body, r) ->

        // `(Show %c)` declares an implementor of arity 0 — an interface trait.
        // `(Monad (%m %a))` writes it applied, which is what no C# interface can
        // express and what makes the trait inline-only.
        let implementorVar, holeArity =
            match implementorSpec with
            | SAtom { Token = QuotedSymbol v } -> v, 0
            | SList (SAtom { Token = QuotedSymbol v } :: holeArgs, hr) ->
                if holeArgs.IsEmpty then
                    failwithf
                        $"Syntax error in def/trait '%s{traitName}' at line %d{hr.Start.Line}: (%%%s{v}) applies the implementor to nothing. Write %%%s{v} instead."
                for a in holeArgs do
                    match a with
                    | SAtom { Token = QuotedSymbol _ } -> ()
                    | _ ->
                        failwithf
                            $"Syntax error in def/trait '%s{traitName}' at line %d{hr.Start.Line}: the implementor may only be applied to type variables."
                v, holeArgs.Length
            | _ ->
                failwithf
                    $"Syntax error in def/trait '%s{traitName}': expected (%s{traitName} %%c) or (%s{traitName} (%%m %%a))."

        let mutable assocTypes = []
        let mutable signatures = []

        for item in body do
            match item with
            // Match: (type 'item)
            | SList (SAtom { Token = Symbol "type" } :: SAtom { Token = QuotedSymbol assocName } :: [], _) ->
                assocTypes <- assocName :: assocTypes
            
            // Match: (: methodName signatureExpr)
            | SList (SAtom { Token = Colon } :: SAtom { Token = Symbol methodName } :: typeExpr :: [], _) ->
                signatures <- (methodName, parseType typeExpr) :: signatures
            
            | _ -> failwithf $"Syntax error in def/trait '%s{traitName}': Expected (type ...) or (: ...)."

        DTrait (traitName, implementorVar, holeArity, List.rev assocTypes, List.rev signatures, r)

    // Parse: (def/impl (TraitName (Vec 'a)) (type 'item 'a) (defun (get v i) ...))
    | SList (SAtom { Token = Symbol "def/impl" } :: 
             SList (SAtom { Token = Symbol traitName } :: targetTypeExpr :: [], _) :: 
             body, r) ->
        
        let targetType = parseType targetTypeExpr
        
        let mutable assocBindings = []
        let mutable methods = []

        for item in body do
            match item with
            // Match: (type 'item targetType)
            | SList (SAtom { Token = Symbol "type" } :: SAtom { Token = QuotedSymbol assocName } :: boundTypeExpr :: [], _) ->
                assocBindings <- (assocName, parseType boundTypeExpr) :: assocBindings
            
            // Match: (defun ...)
            | SList (SAtom { Token = Symbol "defun" } :: _, _) as defunExpr ->
                methods <- parseDecl defunExpr :: methods
            
            | _ -> failwithf $"Syntax error in def/impl for '%s{traitName}': Expected (type ...) or (defun ...)."

        DImpl (traitName, targetType, List.rev assocBindings, List.rev methods, r)

    // Parse: (def/impl/extern (Foldable (Vec 'a)) (type 'item 'a))
    //
    // The bodyless counterpart of `def/impl`, emitted into a library's export
    // metadata so that whoever imports it can resolve the trait's associated
    // types and dispatch to the impl class compiled into that assembly.
    | SList (SAtom { Token = Symbol "def/impl/extern" } ::
             SList (SAtom { Token = Symbol traitName } :: targetTypeExpr :: [], _) ::
             body, r) ->

        let assocBindings =
            body
            |> List.map (function
                | SList (SAtom { Token = Symbol "type" } :: SAtom { Token = QuotedSymbol assocName } :: boundTypeExpr :: [], _) ->
                    assocName, parseType boundTypeExpr
                | _ -> failwithf $"Syntax error in def/impl/extern for '%s{traitName}': Expected (type ...).")

        DImplExtern (traitName, parseType targetTypeExpr, assocBindings, r)

    | _ -> failwithf $"Unknown declaration at line %d{r.Start.Line}"

let parseModule (exprs: SExpr list) : Decl list = List.map parseDecl exprs
