* Bjolang - a language

I think we have all had the thought: all programming languages suck in at least one way. Not all of us think it is a big deal, but some of us feel the urge to try our wings at designing a language. This is my 95% vibe coded try. Not really meant for real use, but to see if my thoughts made any sense.

* Elevator pitch
Bjolang is a scheme-inspired language with local HM type inference that compiles to constipated c#. It has traits instead of classes, meaning you don't ever have to think about two-way interop. The default data structures are immutable. A fast RRB tree (Vec), a very fast CHAMP (hash table), a linked list (List). There are more datastructures coming (ordered map, deque, queue).

It also fakes Brand/higher kinded types by inlining traits when the trait is known at compile time, giving us among other things, a Monad trait. It is eager and non-curried, but has a lambda shorthand.

* Planned features

For concurrency I will integrate a concurrentML because I made this language and async is no fun.

Dynamic environment, meaning we can do things like

#+begin_src scheme
(def my-port (string-port))
(with-output-to-port my-port
  (display "banana boat song!")) ;; displays nothing

(display (string-port->string my-port))

#+end_src

* Limitations

** Entry point
Since it compiles to c# it needs an entry point. That is the (defun (main args) ...) function. 

** Tail recursion

Tail recursion does not work except for self recursion (including named lets) and local mutual recursion.

#+BEGIN_SRC scheme
;; this works

(defun (main args)
  ;; A lazy sequence of fibonaccis
  (def fibseq (seq   
               (let loop ((a 0) (b 1))
                 (yield a)
                 (loop b (+ a b)))))
  (defun (odd? a)
    (match a
      (0 #t)
      (_ (even? (- a 1)))))
  (defun (even? a)
    (if (= 0 a)
        #t
        (odd? (- a 1))))

  ;; This does SCC analysis and transforms the output to
  ;; c# while and switch+goto
  (odd? 4000000)
  0) ;; main needs to return a number


  ;; this stack overflows after a while if you call any of
  ;;the functions. The stack for each of these calls is tiny, but
  ;; you will still only be able to test numbers up to about 100k.
  (: odd? (-> Int Bool)) ;; Every top level function needs a typedef
  (defun (odd? a)
    (if (= 0 a)
        #t
        (even? (- a 1))))

  (: even? (-> Int Bool))
  (defun (even? a)
    (if (= 0 a)
        #t
        (odd? (- a 1))))



#+END_SRC

* Examples
*** Traits
Bjolang has traits. Traits can be regular traits, which means they are usable on concrete types (fast calls) or in dynamic contexts (as fast as C# Interfaces). There are also inlinable traits. These are traits that only work when the type is known at compile time, and are inlined at the call site. This is because c# cannot represent something like the Monad trait with interfaces. Inlining solves this. These traits are painfully monomorphic.

#+begin_src scheme
;; The simplest kind of trait is something like a trait that
;; turns any thing into a string:
(def/trait (Printable %i)
  (: ->str (-> %i string)))

(def/impl (Printable int)
  (defun (->str i) (int->string i)))

;; More complex traits also work:
(def/trait (Foldable %col)
  ;; associated type
  (type %item)
  ;; fold is a function that takes:
  ;; 1. a function that takes an accumulator type, an item type and
  ;;    returns an item type.
  ;; 2. an accumulator type
  ;; 3. a collection type
  ;; 4. and returns an accumulator type.
  (: fold (-> (-> %acc %item %acc) %acc %col %acc)))

;; Implement the trait for a List with a generic in it
(def/impl (Foldable (List %a))
  ;; the associated type %item is the same as the %a in the list
  (type %item %a)
  (defun (fold f acc col)
    (list-foldl f acc col)))

;; fold is now a function that works on a list and any other data
;; type for which Foldable is defined.
(fold #(+ % 1) 0 '(1 2 3 4))

;; This is a "fake hkt" trait: it only works when types are
;; know at compile time and in monomorphic functions.
(def/trait (Functor (%f %a))
  (: fmap (-> (-> %a %b) (%f %a)  (%f %b))))

(def/impl (Functor (List %a))
  (defun (fmap g xs) (list-map g xs))) 

(def/impl (Functor (Option %a))
  (defun (fmap g o)
    (match o ((Some v) (Some (g v))) (None None))))

(defun (main args)
  (def a-list '(1 2 3 4))
  (def an-option (Option 5))
  ;; these both work
  (def b (fmap #(+ &1 1) a-list))
  (def c (fmap #(+ &1 1) an-option))

  (defun (bump bomp)
    (fmap (fun (arg) (+ arg 1)) bomp))

  ;; Works, BUT locks bump into the type (List int)
  (def d (bump a-list))
  ;; Which means this fails because any function written against
  ;; an "inline" trait is going to be monomorphic. 
  (def e (bump an-option))
  0)

#+end_src


*** Do notation
Look Ma, a Monad!

#+BEGIN_SRC scheme
(: calc (-> int (Option int)))
(defun (calc n)
  (do (:bind half (safe-div n 2))
      (:let  doubled (* half 2))
      (:bind third (safe-div doubled 3))
      (:return (+ doubled third))))
#+END_SRC

*** The usual syntactic things in a modern lisp
apart from (-> this is not actually implemented. )

#+begin_src scheme
(-> [1 2 3 4 5]
    (map add1 &)
    (fold + 0 &)
    println)

;; in fact, any flat expr with & turns into a lambda. at least when I have gotten to implementing it. 

(+ & 5) ;; => (fun (&1) (+ &1 5))
#+end_src

if-let, some-let* and things are going to be implemented.

some-> will short-circuit in any of the calls returns none.


*** Immutable base data structures
 Bjolang's base data structures are all immutable and fast (yes, actually fast). These data structures are _not_ vibe coded like this project. Not only are they fast in their immutable versions, but they also have transient versions.

 The Vec type is an RRB vector. It compares favourably to the immutable vectors of clojure an  scala. If you don't count the "slices" of clojure's vectors (which are just views), it is a lot faster than clojure's vectors. The slices of scala's vectors has magic finger tree pixie dust, but other than that it competes (and often wins) with regards to speed.

 The Map is a CHAMP that has transient operations and a builder. It compares favourably to the immutable map in c# or the hash map in language-ext.

 #+begin_src scheme
(defun (main args)
  (def a-map #map((:banana "fruit") (:volvo "car") (:mercedes "car") (:anna-karenina "neither")))
  (def b-map  (map-filter #(equal? &2 "neither") a-map))
  (println (map-count b-map)) ;; 1
  (println (map-count a-map)) ;; 3
  
 #+end_src

*** Keyword arguments
Unlike f#, bjolang has keyword arguments (but no optargs!):

#+begin_src scheme
(: key-fun (-> Int (#:what string) Void))
(defun (key-fun times #:what (string-append "ban" "ana"))
  (let loop ((times times))
    (when (> times 0)
      (println what)
      (loop (- times 1)))))

(key-fun 100) ;; prints "banana\n" 100 times
(key-fun 10 #:what "orange") ;; prints "orange\n" 10 times
#+end_src

This is currently less efficient than non-kw functions, because every function call checks what was provided and re-evaluates the default argument expressions. It is just a series of ifs and evaluating the expressions, so it is not that bad, but perhaps something that could be added.

*** Structs and records
Have the same syntax, and both are constructed by naming the type — there is no
f#-esque guessing at which type a bag of field names belongs to. This is a
record example:

#+begin_src scheme
(type
 (: Colors (Enum Red Green Brown Golden))
 (: Fruit (Record
           (: name String)
           (: has-peel? Bool)
           (: colour Colors))))
 
(def banana (Fruit (name "banana") (has-peel? #t) (colour Golden)))
(def megaripe-banana (record-set banana (colour Brown))

#+end_src

*** Pattern matching
#+begin_src scheme
(match operation
  ((Some 5) (println "it returned 5!!!"))
  ((Some a) (print "It returned ") (println a))
  (None (println "something went wrong")))

(match a-list
  ((List 1 2 3) 1)
  ((List 1 2 _) 2)
  ((List a b c) (+ a (+ b c)))
#+end_src

*** A proper looping facility

I got tired of shitty looping facilities a long time ago. I took Alex Shinn's (chibi loop) and made (goof loop) for guile scheme. Not only was it extensible and much more flexible than most looping facilities, it also had the fantastic feature that the code it produced was as fast as a hand-rolled loop (looking at you, python's for loop).

Bjolangs loop is based on what I learned writing goof-loop, but instead of using macros, it uses traits meaning it sucks a bit more. 

#+begin_src scheme
(defun (main args)
  (def my-vec (get-a-huge-vec))
  (def my-list (get-an-equally-huge-list))
  (loop (:for a my-vec)
        (:for b my-vec)
        (:break (= a (* b 2)))
        (:when (not (= a b)))
        (:acc acc (listing (+ a b)))))
#+end_src

It also supports subloops. Anything that isn't a for clause followed by a :for clause starts a subloop:

#+begin_src scheme
(defun (main args)
  (loop (:for a '(1 2 3))
        (:when (odd? a))
        (:for b [1 2])
        (:acc (vectoring (a . b)))))
;; => [(1 1) (1 2) (3 1) (3 2)]
#+end_src

 And the best part? It is fast.

 Oh, and it also has a seq version

 #+begin_src scheme
(defun (main args)
  (def all-fibs
    (seql (:with a 0L b)
          (:with b 1L (+ a b))
          (:yield a))))
  (println "I wonder if we can print all the fibonacci numbers up to 2^64-1")
  (seq-for-each #(println &) all-fibs))
 #+end_src

*** Dotnet interop
If you want to call c# it is possible:

#+begin_src scheme
(import/extern
  (write-line (: System.Console.WriteLine (-> string void)))
  (concat2 (: System.String.Concat (-> string string string))))

(write-line (concat2 "hej" " hej"))

;; and for classes


(import/class
  (StreamWriter (: System.IO.StreamWriter (-> string StreamWriter))))

(def my-stream (StreamWriter. "a-file"))
(.Write my-stream "banana")
(.Flush my-stream)
(.Dispose my-stream)
#+end_src

*** Constructorless DSLs

Lists, quasiquoted lists and vectors do not need constructors in some circumstances, giving us nice small DSLs, like the (run ...) function DSL:

#+begin_src scheme

(:stream-rot13 (-> InputPort OutputPort Void))
;; implementation left as an exercise for the reader

(run/strings '(pipe (cat "encrypted-file.txt") ,stream-rot13 (grep "bomb")))
;; Without the constructor insertions it would be:
(run/strings (ProcList (ProcSym 'pipe)
               (ProcList (ProcSym 'cat) (ProcString "encrypted-file.txt"))
               (ProcProc stream-rot13)
               (ProcList (ProcSym 'grep) (ProcString "bomb")))))
#+end_src

* TODO

These are things I found while spelunking:

- Check that the Map higher order wrappers are not slowing things down too much
- Make it possible to shadow trait methods and not have the typechecker vomit.
- output LINE-directives so that we can see which code generated the bad c# output if roslyn fails.
- Dynamic environment. 
- ConcurrentML. Preferably fast and not built on the full Task machinery. 
- A standard library that doesn't suck.
- seq being a trait: seq-map(etc) should work on every collection lazily.
- Annotations using @[c# annotation verbatim here] so that I can piggyback on c# json libraries.
- an (import/extern ...) form that could look like this:

  #+begin_src scheme
(import/extern (print-int    (: System.Console.WriteLine (-> int void)))
               (print-double (: System.Console.WriteLine (-> double void))))

  #+end_src

** Things I need in the standard library
DONE Integrate the BjoChar character in the compiler. Literals =#\a=, named
characters, =#\xNN= hex escapes and astral codepoints all lex to a 32-bit
scalar value; =char= is a type, patterns match on it, and =char->int=,
=int->char= and =char->string= convert. Covered by =67_char.bjo=.

Deliberately *not* done: =string-ref= and other index-based string operations.
Indexing a UTF-16 string by codepoint is O(n), so a loop that looks linear is
quadratic — string traversal belongs to a cursor.

typed string interpolation

Stringbuilders.

IO for working with files

io for working with network thingies

Deque and Heap, preferrably with transient interfaces

Process notation, maybe taken from scsh.

String functions in general. Add (stringing c) to loop.

Maybe I should just steal all the functions from r6rs and bolt them onto what I can find in dotnet. Or maybe steal something from racket.

STRING FORMATTING. Alex Shinn is the answer yet again. (show #t etc ...) and divide them into shorter forms showt and showf and make them the "default" print functions. I really like the showt name...

** Syntax ideas
@-expr from racket?

comprehensions based on loop. This is simple. I should do it now (early august 2026):

#+begin_src scheme
{listing (+ a 5) :for a b}
;; would become
(loop (:for a b)
      (:acc gensym-here (listing (+ a 5))))

;; but also allow for more
{vecing (abs (- b f) :when (sun-and-moon-in-zenith) :for b (get-infinite-seq) :break (> b 2) :for f (stuffy-stuff b)))}
;; which becomes
(loop (:for b (get-infinite-seq))
      (:break (> b 2))
      (:for f (stuffy-stuff b))
      (:acc gensym-here (abs (- b f)) :when (sun-and-moon-in-zenith)))

;; The seql version would just {seqing expr :for ...}
#+end_src

Extend do notation to be more usable. :match :traverse :and<- (seems _very hard_ atm).

(with-return ...) that allows for (return ...). Disallowed in loops and seq. 


** Things to fix:

Naming a local variable list, will produce local shadowing and a c# exception. I need to hook in the alpharenamer.

'(1 2 3) and (list 1 2 3) produces different code.

[1 2 3 4] should codegen an array that is put directly into the tail, or split and inserted in chunks of 32. 


