;; k-nucleotide.
(import (chezscheme))

(define (code c)
  (case c
    ((#\a #\A) 0)
    ((#\c #\C) 1)
    ((#\g #\G) 2)
    (else 3)))

(define (starts-with? s prefix)
  (and (fx>= (string-length s) (string-length prefix))
       (string=? (substring s 0 (string-length prefix)) prefix)))

(define (read-sequence in)
  (let skip ()
    (let ((line (get-line in)))
      (unless (or (eof-object? line) (starts-with? line ">THREE"))
        (skip))))
  (let-values (((sp get) (open-string-output-port)))
    (let go ()
      (let ((line (get-line in)))
        (unless (or (eof-object? line) (starts-with? line ">"))
          (put-string sp line)
          (go))))
    (let* ((s (get))
           (n (string-length s))
           (sq (make-bytevector n)))
      (do ((i 0 (fx+ i 1))) ((fx= i n))
        (bytevector-u8-set! sq i (code (string-ref s i))))
      sq)))

(define (count-kmers sq k)
  (define counts (make-eqv-hashtable))
  (define mask (fx- (fxsll 1 (fx* 2 k)) 1))
  (define n (bytevector-length sq))
  (let go ((i 0) (key 0))
    (when (fx< i n)
      (let ((key (fxand (fxior (fxsll key 2) (bytevector-u8-ref sq i)) mask)))
        (when (fx>= i (fx- k 1))
          (hashtable-update! counts key (lambda (c) (fx+ c 1)) 0))
        (go (fx+ i 1) key))))
  counts)

(define (key->string key k)
  (let ((s (make-string k)))
    (do ((i 0 (fx+ i 1))) ((fx= i k))
      (string-set! s (fx- k 1 i)
                   (string-ref "ACGT" (fxand (fxsra key (fx* 2 i)) 3))))
    s))

(define (string->key s)
  (let loop ((i 0) (key 0))
    (if (fx< i (string-length s))
        (loop (fx+ i 1) (fxior (fxsll key 2) (code (string-ref s i))))
        key)))

(define (write-frequencies sq k)
  (let* ((counts (count-kmers sq k))
         (total (fixnum->flonum (fx- (fx+ (bytevector-length sq) 1) k)))
         (entries (let-values (((keys vals) (hashtable-entries counts)))
                    (map (lambda (key v) (cons v (key->string key k)))
                         (vector->list keys) (vector->list vals))))
         (sorted (sort (lambda (a b)
                         (or (fx> (car a) (car b))
                             (and (fx= (car a) (car b)) (string<? (cdr a) (cdr b)))))
                       entries)))
    (for-each (lambda (e)
                (printf "~a ~,3f\n" (cdr e) (fl/ (fl* 100.0 (fixnum->flonum (car e))) total)))
              sorted)
    (newline)))

(define (write-count sq name)
  (let ((counts (count-kmers sq (string-length name))))
    (printf "~a\t~a\n" (hashtable-ref counts (string->key name) 0) name)))

(let ((sq (read-sequence (current-input-port))))
  (write-frequencies sq 1)
  (write-frequencies sq 2)
  (for-each (lambda (name) (write-count sq name))
            '("GGT" "GGTA" "GGTATT" "GGTATTTTAATT" "GGTATTTTAATTTATAGT")))
