;; pidigits, with Chez's own bignums.
(import (chezscheme))

(define (pidigits n)
  (let go ((i 0) (k 0) (acc 0) (den 1) (num 1))
    (when (< i n)
      (let* ((k (+ k 1))
             (k2 (+ (* 2 k) 1))
             (acc (* (+ acc (* num 2)) k2))
             (den (* den k2))
             (num (* num k)))
        (if (> num acc)
            (go i k acc den num)
            (let ((d (quotient (+ (* num 3) acc) den)))
              (if (not (= d (quotient (+ (* num 4) acc) den)))
                  (go i k acc den num)
                  (let ((i (+ i 1)))
                    (write-char (integer->char (+ 48 d)))
                    (when (= 0 (remainder i 10))
                      (printf "\t:~a\n" i))
                    (go i k (* (- acc (* den d)) 10) den (* num 10)))))))))
  (unless (= 0 (remainder n 10))
    (display (make-string (- 10 (remainder n 10)) #\space))
    (printf "\t:~a\n" n)))

(pidigits (string->number (cadr (command-line))))
(flush-output-port (current-output-port))
