<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="RrbList\**" />
    <Compile Remove="Map\**" />
    <Compile Remove="SchemeList\**" />
    <EmbeddedResource Remove="RrbList\**" />
    <EmbeddedResource Remove="Map\**" />
    <EmbeddedResource Remove="SchemeList\**" />
    <None Remove="RrbList\**" />
    <None Remove="Map\**" />
    <None Remove="SchemeList\**" />
    <ProjectReference Include="RrbList/src/Collections/Collections.csproj" />
    <ProjectReference Include="SchemeList/src/SchemeList/SchemeList.csproj" />
    <ProjectReference Include="Map/Map/Map.csproj" />
  </ItemGroup>
</Project>
